apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
    {{- include "mlflow.postgres.selectorLabels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.postgres.secretKey }}: {{ .Values.postgres.defaultPassword | b64enc | quote }}
