"""Vocabulary lists for prompt optimization and CEFR evaluation.

Ported from inference/src/evaluate_prompts.py to be self-contained.
"""
from __future__ import annotations

A1_WORDS = frozenset([
    "abend", "abendessen", "aber", "acht", "alle", "allein", "alles", "alt",
    "an", "antworten", "apfel", "apotheke", "arbeit", "arbeiten", "arzt", "auch",
    "auf", "auf Wiedersehen", "auge", "aus", "ausbildung", "auto",
    "bahn", "bahnhof", "ball", "banane", "bank", "baum", "beide", "beim",
    "bein", "beispiel", "beißen", "bekommen", "bereit", "berg", "beruf", "bett",
    "bezahlen", "bier", "bild", "billig", "bin", "birne", "bist", "bitte",
    "blau", "bleiben", "bleistift", "blume", "boden", "brot", "bruder", "buch",
    "bus", "butter", "café", "computer", "da", "danke", "dann", "darf",
    "das", "dein", "dem", "den", "denken", "der", "des", "deutsch",
    "dialog", "dich", "die", "dienstag", "ding", "dir", "doch", "donnerstag",
    "dort", "drei", "du", "dunkel", "durch", "duschen", "durst", "ecke",
    "ei", "ein", "eine", "einem", "einen", "einer", "eines", "einfach",
    "einladen", "einkaufen", "einmal", "eis", "eltern", "ende", "englisch", "entschuldigung",
    "er", "erde", "erst", "es", "essen", "euch", "euer", "fahren",
    "fahrrad", "familie", "fast", "vater", "fehlen", "fenster", "ferien", "fernsehen",
    "fertig", "feuer", "finden", "fisch", "flasche", "fleisch", "fliegen", "flughafen",
    "flugzeug", "fluss", "fragen", "frau", "frei", "freitag", "freizeit", "freund",
    "freundin", "frisch", "froh", "früh", "frühling", "frühstück", "für", "fuß",
    "fußball", "geben", "gegen", "gehen", "gelb", "geld", "gemüse", "genug",
    "gern", "gerne", "gespräch", "gesund", "glauben", "groß", "großeltern", "grün",
    "gut", "guten", "haar", "haben", "habt", "hallo", "hand", "handy",
    "hast", "hat", "hatte", "haus", "heiß", "helfen", "herbst", "herr",
    "heute", "hier", "himmel", "hinter", "hobby", "hoch", "holen", "hören",
    "hotel", "hund", "hunger", "ich", "ihm", "ihn", "ihr", "immer",
    "in", "ist", "ja", "jahr", "jeder", "jetzt", "jung", "kaffee",
    "kalt", "kann", "karte", "kartoffel", "käse", "kaufen", "kein", "keine",
    "kind", "kino", "klasse", "klein", "kochen", "koffer", "kollege", "kommen",
    "können", "kopf", "kosten", "krank", "krankenhaus", "küche", "kuchen", "kugelschreiber",
    "kurz", "lachen", "laden", "land", "lang", "langsam", "laufen", "laut",
    "leben", "legen", "lehrer", "leicht", "leise", "lernen", "lesen", "letzte",
    "leute", "licht", "lieb", "lieben", "lieber", "liegen", "links", "luft",
    "lustig", "machen", "mädchen", "mann", "markt", "mehr", "mein", "mensch",
    "messer", "milch", "minute", "mit", "mitbringen", "mittag", "mittagessen", "mitte",
    "mittwoch", "möchte", "mitnehmen", "monat", "montag", "morgen", "müde", "mund",
    "musik", "müssen", "mutter", "nach", "nachmittag", "nah", "name", "natur",
    "neben", "nehmen", "nein", "nennen", "nett", "neu", "neun", "nicht",
    "nichts", "nie", "noch", "nudeln", "nummer", "nur", "ob", "obst",
    "oder", "offen", "öffnen", "oft", "ohne", "onkel", "orange", "ort",
    "papier", "park", "partner", "person", "pfeffer", "pferd", "platz", "post",
    "preis", "problem", "rad", "regen", "regnen", "reich", "reise", "reisen",
    "restaurant", "richtig", "riechen", "rot", "rufen", "ruhig", "rund", "sache",
    "saft", "sagen", "salat", "salz", "samstag", "sauber", "sauer", "schade",
    "schlafen", "schlecht", "schließen", "schlüssel", "schmecken", "schmutzig", "schnee", "schnell",
    "schon", "schön", "schreiben", "schuh", "schule", "schüler", "schwarz", "schwer",
    "schwester", "schwimmen", "sechs", "see", "sehen", "sehr", "seid", "sein",
    "seit", "seite", "selbst", "senden", "sessel", "sich", "sie", "sieben",
    "sind", "singen", "sitzen", "sohn", "sommer", "sonne", "sonntag", "spaß",
    "spät", "spazieren", "speisekarte", "spielen", "sport", "sprechen", "stadt", "stand",
    "stark", "stehen", "stelle", "stellen", "stift", "straße", "stück", "stuhl",
    "suchen", "suppe", "süß", "tag", "tante", "tasche", "tasse", "tee",
    "telefon", "teller", "teuer", "tief", "tier", "tisch", "tochter", "toll",
    "tomate", "tragen", "treffen", "trinken", "tschüss", "tür", "uhr", "über",
    "um", "und", "uns", "unser", "unter", "urlaub", "verkaufen", "verstehen",
    "viel", "vielleicht", "vier", "vom", "von", "vor", "vormittag", "wagen",
    "wald", "wann", "warm", "warum", "was", "waschen", "wasser", "weg",
    "weich", "wein", "weit", "weiter", "welt", "wenig", "wer", "werden",
    "werfen", "wetter", "wichtig", "wie", "wieder", "will", "wind", "winter",
    "wir", "wissen", "wo", "woche", "wochenende", "woher", "wohin", "wohnen",
    "wohnung", "wollen", "wort", "wunderbar", "zahlen", "zahn", "zehn", "zeigen",
    "zeit", "zeitung", "zimmer", "zu", "zucker", "zug", "zusammen", "zwei",
    "zwischen",
    # Additional conjugated verbs and dialogue vocabulary for CEFR matching
    "möchten", "möchtest", "möchtet", "kannst", "können", "könnt", "könnte", "könnten",
    "muss", "musst", "müssen", "müsst", "soll", "sollst", "sollen", "sollt",
    "will", "willst", "wollen", "wollt", "darf", "darfst", "dürfen", "dürft",
    "werde", "wirst", "wird", "werden", "werdet", "war", "warst", "waren", "wart",
    "hattest", "hatten", "hattet", "trinke", "trinkst", "trinkt", "trinket",
    "esse", "isst", "esst", "esset", "gehe", "gehst", "geht", "gehet",
    "komme", "kommest", "kommte", "kommet", "nehme", "nimmst", "nimmt", "nehmet",
    "kaufe", "kaufst", "kauft", "kaufet", "zahle", "zahlst", "zahlt", "zahlet",
    "bringe", "bringst", "bringt", "bringen", "bringet", "warte", "wartest",
    "wartet", "warten", "pizza", "cola", "rechnung", "bestellen", "vielen", "dank"
])

B2_WORDS = frozenset([
    "ablehnen", "absehbar", "absolvieren", "abstimmen", "abwechslungsreich", "allerdings",
    "allmählich", "alltäglich", "analysieren", "anforderung", "angemessen", "ankommen",
    "anerkennen", "anliegen", "annehmen", "anspruch", "anteil", "anwendung",
    "argument", "argumentation", "art", "assoziation", "atmosphäre", "auffassung",
    "aufgabe", "aufheben", "aufklären", "aufmerksam", "aufnahme", "aufwand",
    "ausbildung", "ausdrücken", "auseinandersetzen", "ausgehen", "ausgleich", "ausnahme",
    "ausreichen", "auswirkung", "beabsichtigen", "bedauern", "bedauerlicherweise", "bedeutung",
    "beeinflussen", "beeinträchtigen", "befassen", "befürworten", "begeistern", "begründen",
    "behaupten", "beinahe", "beitrag", "bekanntlich", "belegen", "bemühen",
    "benötigen", "berücksichtigen", "berufstätig", "beschäftigen", "bescheiden", "beschließen",
    "beschränken", "beschweren", "besitzen", "besorgt", "besprechen", "bestätigen",
    "bestehen", "bestimmen", "beteiligen", "betonen", "betrachten", "betreffen",
    "betreuen", "beurteilen", "bevölkerung", "bevorzugen", "bewerten", "bewusst",
    "bewusstsein", "beziehen", "beziehung", "beziehungsweise", "bezug", "bieten",
    "bildung", "bislang", "bitten", "bleiben", "darlegen", "darstellen",
    "dazu", "definieren", "dementsprechend", "demnach", "demzufolge", "dennoch",
    "deutlich", "differenzieren", "diskutieren", "durchführen", "durchsetzen", "ebenso",
    "ehemalig", "eindeutig", "einfluss", "einführen", "eingreifen", "einheit",
    "einschätzen", "einverstanden", "einzeln", "einzigartig", "empfehlen", "engagieren",
    "entdecken", "entgegen", "enthalten", "entscheiden", "entscheidung", "entschließen",
    "entsprechen", "entsprechend", "entstehen", "entwickeln", "entwicklung", "entwerfen",
    "erachten", "erfahren", "erfahrung", "erfassen", "erfinden", "erfolgreich",
    "erforderlich", "erfreulicherweise", "ergänzen", "ergebnis", "erheblich", "erhöhen",
    "erkennen", "erkenntnis", "erklären", "erlauben", "erläutern", "erleichtern",
    "ermöglichen", "ernähren", "ernsthaft", "eröffnen", "erörtern", "erreichen",
    "erscheinen", "erschweren", "ersetzen", "erstklassig", "erwarten", "erwartung",
    "erwerben", "erzielen", "eventuell", "fähig", "fähigkeit", "fazit",
    "feststellen", "finanzieren", "folglich", "fördern", "forderung", "fortbildung",
    "fortschritt", "garantieren", "geeignet", "gefährden", "gegenüber", "gelegenheit",
    "geltend", "gemeinsam", "gemeinschaft", "genießen", "geradezu", "gerecht",
    "gering", "gesamt", "gesellschaft", "gesetzlich", "gestalten", "gewährleisten",
    "gewiss", "gewissermaßen", "gleichwohl", "grenze", "grundlage", "grundsätzlich",
    "häufig", "hauptsächlich", "herausforderung", "hervorragend", "hinsichtlich", "hinweisen",
    "infolgedessen", "infrage", "inhalt", "initiative", "insofern", "insbesondere",
    "interesse", "interpretieren", "investieren", "jedenfalls", "jedoch", "jeweils",
    "keineswegs", "kenntnis", "klarstellen", "komplex", "kompliziert", "konflikt",
    "konsequenz", "konsequent", "kritisieren", "kulturell", "künftig", "lage",
    "langfristig", "lebenslauf", "lediglich", "leisten", "leistung", "letztendlich",
    "maßnahme", "meinung", "merkwürdig", "methode", "mittlerweile", "möglich",
    "möglichkeit", "nachweisen", "nachhaltig", "nämlich", "notwendig", "nichtsdestotrotz",
    "nichtsdestoweniger", "nutzen", "obwohl", "offenbar", "optimieren", "organisieren",
    "perspektive", "planen", "prinzip", "prinzipiell", "prozess", "rahmenbedingung",
    "realisieren", "reagieren", "regelung", "relevant", "risiko", "rolle",
    "schwierig", "schwierigkeit", "selbstverständlich", "sicherlich", "sinnvoll", "somit",
    "sozial", "spezifisch", "ständig", "stattfinden", "stattdessen", "stellungnahme",
    "struktur", "tatsächlich", "teilnehmen", "tendenz", "überprüfen", "übrigens",
    "umsetzen", "umstand", "unbedingt", "uneinig", "unerwartet", "unglücklicherweise",
    "unmittelbar", "unterscheiden", "unterschied", "untersuchen", "unterstützen",
    "verändern", "veränderung", "verantwortung", "verbessern", "verbindung", "verbreiten",
    "vereinbaren", "vereinbarung", "verfügen", "vergleichen", "verhandlung", "verhältnis",
    "verhältnismäßig", "verlangen", "verlauf", "vermeiden", "vermuten", "vermutlich",
    "verringern", "verursachen", "voraussetzung", "vorbereiten", "vorgehen", "vorschlagen",
    "vorteil", "wahrscheinlich", "wechseln", "wesentlich", "widerlegen", "wirkung",
    "wirtschaft", "wissenschaft", "zahlreich", "zielsetzung", "zudem", "zufolge",
    "zufrieden", "zusammenhang", "zuständig", "zustimmen", "zuverlässig", "zweifel",
    "zweifellos", "anforderung", "erwartung"
])
